/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_canonical_openssl_key_KeyConverter */

#ifndef _Included_com_canonical_openssl_key_KeyConverter
#define _Included_com_canonical_openssl_key_KeyConverter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_canonical_openssl_key_KeyConverter
 * Method:    privateKeyToEVPKey0
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_canonical_openssl_key_KeyConverter_privateKeyToEVPKey0
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_canonical_openssl_key_KeyConverter
 * Method:    publicKeyToEVPKey0
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_canonical_openssl_key_KeyConverter_publicKeyToEVPKey0
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_canonical_openssl_key_KeyConverter
 * Method:    freeEVPKey0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_canonical_openssl_key_KeyConverter_freeEVPKey0
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif

