/*
 * Copyright (C) Canonical, Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_canonical_openssl_keypairgenerator_OpenSSLKeyPairGenerator */

#ifndef _Included_com_canonical_openssl_keypairgenerator_OpenSSLKeyPairGenerator
#define _Included_com_canonical_openssl_keypairgenerator_OpenSSLKeyPairGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_canonical_openssl_keypairgenerator_OpenSSLKeyPairGenerator
 * Method:    generateKeyPair0
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_com_canonical_openssl_keypairgenerator_OpenSSLKeyPairGenerator_generateKeyPair0
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
