/*
 * Copyright (C) Canonical, Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_canonical_openssl_kdf_OpenSSLPBKDF2 */

#ifndef _Included_com_canonical_openssl_kdf_OpenSSLPBKDF2
#define _Included_com_canonical_openssl_kdf_OpenSSLPBKDF2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_canonical_openssl_kdf_OpenSSLPBKDF2
 * Method:    generateSecret0
 * Signature: ([B[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_canonical_openssl_kdf_OpenSSLPBKDF2_generateSecret0
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint);

JNIEXPORT jint JNICALL Java_com_canonical_openssl_kdf_OpenSSLPBKDF2_getMaxKeyLengthBytes0
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
